In [4]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile, join

data_path = 'data/'
onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path,f))]

Training_Data, Labels = [], []

for i, files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images, dtype=np.uint8))
    Labels.append(i)

Labels = np.asarray(Labels, dtype=np.int32)

model = cv2.face.LBPHFaceRecognizer_create()

model.train(np.asarray(Training_Data), np.asarray(Labels))

print("Model Training Complete!!!!!")

face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_detector(img, size = 0.5):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if faces is():
        return img,[]

    for(x,y,w,h) in faces:
        cv2.rectangle(img, (x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        print(roi)
        roi = cv2.resize(roi, (200,200))
        

    return img,roi

cap = cv2.VideoCapture(0)
while True:

    ret, frame = cap.read()

    image, face = face_detector(frame)

    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        result = model.predict(face)

        if result[1] < 500:
            confidence = int(100*(1-(result[1])/300))
            display_string = str(confidence)+'% Confidence it is user'
        cv2.putText(image,display_string,(100,120), cv2.FONT_HERSHEY_COMPLEX,1,(250,120,255),2)


        if confidence > 75:
            cv2.putText(image, "Unlocked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            cv2.imshow('Face Cropper', image)

        else:
            cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 255), 2)
            cv2.imshow('Face Cropper', image)


    except:
        cv2.putText(image, "Face Not Found", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)
        cv2.imshow('Face Cropper', image)
        pass

    if cv2.waitKey(1)==13:
        break


cap.release()
cv2.destroyAllWindows()

Model Training Complete!!!!!
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [154 161 161]
  ...
  [ 97  96  92]
  [111 110 106]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [139 143 143]
  ...
  [102 125 121]
  [ 99 122 118]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [129 145 143]
  ...
  [102 125 121]
  [101 124 120]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [155 157 157]
  ...
  [103 117 115]
  [107 121 119]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 

[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [153 146 141]
  ...
  [134 141 141]
  [133 140 139]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [145 147 147]
  ...
  [123 132 132]
  [124 131 130]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [146 148 148]
  ...
  [121 130 130]
  [119 130 129]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [ 48  47  43]
  ...
  [129 140 140]
  [127 141 140]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [143 147 147]
  ..

[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [155 159 159]
  ...
  [ 25  28  24]
  [ 25  28  24]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [142 146 146]
  ...
  [124 131 131]
  [123 130 130]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [143 147 147]
  ...
  [124 131 131]
  [122 129 129]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [156 163 162]
  ...
  [ 90  89  85]
  [106 105 101]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [145 147 147]
  ..

[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [ 45  41  40]
  ...
  [ 19  23  22]
  [ 19  23  22]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [139 143 143]
  ...
  [112 128 127]
  [114 130 129]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [141 145 145]
  ...
  [112 128 127]
  [114 130 129]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]
[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [157 158 162]
  ...
  [ 26  28  22]
  [ 27  29  23]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [143 143 143]
  ..